version: "3"
services:
  backend:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    ports:
      - '3000:3000'
    restart: always
    container_name: server
  frontend:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    ports:
      - '80:80'
    restart: always
    container_name: app